# Generated by Django 6.0.5 on 2026-05-23 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_article_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='After',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side1_casualties', models.CharField(max_length=255)),
                ('side1_captured', models.CharField(max_length=255)),
                ('side1_equipmentLoss', models.CharField(max_length=255)),
                ('side1_supplyLoss', models.CharField(max_length=255)),
                ('side2_casualties', models.CharField(max_length=255)),
                ('side2_captured', models.CharField(max_length=255)),
                ('side2_equipmentLoss', models.CharField(max_length=255)),
                ('side2_supplyLoss', models.CharField(max_length=255)),
                ('TacticalReform', models.TextField()),
                ('DoctrineChange', models.TextField()),
                ('MoraleEffect', models.TextField()),
                ('HistoricalImpact', models.TextField()),
                ('MilitaryInfluence', models.TextField()),
                ('LongTermConsequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Before',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side1_Name', models.CharField(max_length=255)),
                ('side1_troops', models.CharField(max_length=255)),
                ('side1_infantry', models.CharField(max_length=255)),
                ('side1_cavalry', models.CharField(max_length=255)),
                ('side1_veterans', models.CharField(max_length=255)),
                ('side1_morale', models.CharField(max_length=255)),
                ('side1_food', models.CharField(max_length=255)),
                ('side1_supplyLoss', models.CharField(max_length=255)),
                ('side1_armor', models.CharField(max_length=255)),
                ('side1_mountedUnits', models.CharField(max_length=255)),
                ('side1_mainRoute', models.CharField(max_length=255)),
                ('side1_routeLength', models.CharField(max_length=255)),
                ('side1_contested', models.CharField(max_length=255)),
                ('side1_supplyDelay', models.CharField(max_length=255)),
                ('side2_Name', models.CharField(max_length=255)),
                ('side2_troops', models.CharField(max_length=255)),
                ('side2_infantry', models.CharField(max_length=255)),
                ('side2_cavalry', models.CharField(max_length=255)),
                ('side2_veterans', models.CharField(max_length=255)),
                ('side2_morale', models.CharField(max_length=255)),
                ('side2_food', models.CharField(max_length=255)),
                ('side2_supplyLoss', models.CharField(max_length=255)),
                ('side2_armor', models.CharField(max_length=255)),
                ('side2_mountedUnits', models.CharField(max_length=255)),
                ('side2_mainRoute', models.CharField(max_length=255)),
                ('side2_routeLength', models.CharField(max_length=255)),
                ('side2_contested', models.CharField(max_length=255)),
                ('side2_supplyDelay', models.CharField(max_length=255)),
                ('Terrain', models.CharField(max_length=30)),
                ('Weather', models.CharField(max_length=30)),
                ('Visibility', models.CharField(max_length=30)),
                ('Mobility', models.CharField(max_length=30)),
                ('commander1_name', models.CharField(max_length=255)),
                ('commander1_SuccessfulDecisions', models.TextField()),
                ('commander1_FailedDecisions', models.TextField()),
                ('commander2_name', models.CharField(max_length=255)),
                ('commander2_successfulDecisions', models.TextField()),
                ('commander2_FailedDecisions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='During',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TurningPoint', models.TextField()),
                ('side1_battlePressure', models.CharField(max_length=255)),
                ('side2_battlePressure', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='content',
            new_name='Importance',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='title',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='summary',
        ),
        migrations.AddField(
            model_name='articles',
            name='Victor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='Year',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='after',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.after'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='before',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.before'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='during',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.during'),
            preserve_default=False,
        ),
    ]
