# Generated by Django 6.0.5 on 2026-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_articles_after_remove_articles_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='criticalMistakes1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='criticalMistakes2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='criticalMistakes3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='criticalMistakes4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='criticalMistakes5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_action9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_strength9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName10',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName3',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName4',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName5',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName6',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName7',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName8',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_unitName9',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_weakness9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_action9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_strength9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName10',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName3',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName4',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName5',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName6',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName7',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName8',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_unitName9',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
