# Generated by Django 6.0.5 on 2026-05-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articles_criticalmistakes1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='slug',
            new_name='Slug',
        ),
        migrations.AddField(
            model_name='articles',
            name='Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
