# Generated by Django 6.0.5 on 2026-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_author_articles_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Tag1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='articles',
            name='Tag2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='articles',
            name='Tag3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='articles',
            name='Tag4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='articles',
            name='Tag5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
