# Generated by Django 6.0.5 on 2026-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_tag1_articles_tag2_articles_tag3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action1',
            new_name='commander1_FailedDecisions1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action10',
            new_name='commander1_FailedDecisions2',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action2',
            new_name='commander1_FailedDecisions3',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action3',
            new_name='commander1_FailedDecisions4',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action4',
            new_name='commander1_FailedDecisions5',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action5',
            new_name='commander1_SuccessfulDecisions1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action6',
            new_name='commander1_SuccessfulDecisions2',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action7',
            new_name='commander1_SuccessfulDecisions3',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action8',
            new_name='commander1_SuccessfulDecisions4',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='side1_action9',
            new_name='commander1_SuccessfulDecisions5',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='commander1_FailedDecisions',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='commander1_SuccessfulDecisions',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength10',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength4',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength5',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength6',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength7',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength8',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_strength9',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness10',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness4',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness5',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness6',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness7',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness8',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side1_weakness9',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action10',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action4',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action5',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action6',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action7',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action8',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_action9',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_contested',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength10',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength4',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength5',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength6',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength7',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength8',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_strength9',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_supplyDelay',
        ),
        migrations.AddField(
            model_name='articles',
            name='Move1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move10',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move6',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move7',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move8',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='Move9',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength10',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength6',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength7',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength8',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='strength9',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness10',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness5',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness6',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness7',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness8',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articles',
            name='weakness9',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Author',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='articles',
            name='DoctrineChange',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='HistoricalImpact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Importance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='LongTermConsequence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='MilitaryInfluence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Mobility',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='MoraleEffect',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='TacticalReform',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Terrain',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Victor',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Visibility',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Weather',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Year',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='commander1_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='commander2_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_armor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_battlePressure',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_captured',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_casualties',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_cavalry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_contested',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_equipmentLoss',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_food',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_infantry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_mainRoute',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_morale',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_mountedUnits',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_routeLength',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_supplyDelay',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_supplyLoss',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_troops',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_veterans',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_armor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_battlePressure',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_captured',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_casualties',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_cavalry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_equipmentLoss',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_food',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_infantry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_mainRoute',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_morale',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_mountedUnits',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_routeLength',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_supplyLoss',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_troops',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_veterans',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
