# Generated by Django 6.0.5 on 2026-06-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_side1_action1_articles_commander1_faileddecisions1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='commander2_FailedDecisions',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='commander2_successfulDecisions',
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_failedDecisions1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_failedDecisions2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_failedDecisions3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_failedDecisions4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_failedDecisions5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_successfulDecisions1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_successfulDecisions2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_successfulDecisions3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_successfulDecisions4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='commander2_successfulDecisions5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer10',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer3',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer4',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer5',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer6',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer7',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer8',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_officer9',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer10',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer3',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer4',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer5',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer6',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer7',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer8',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_officer9',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
