# Generated by Django 6.0.5 on 2026-06-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articles_mobility_alter_articles_move1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='side1_battlePressure',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='side2_battlePressure',
        ),
        migrations.AddField(
            model_name='articles',
            name='side1_Menance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='side2_Menance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Move9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_captured',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_casualties',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_equipmentLoss',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side1_supplyLoss',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_captured',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_casualties',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_equipmentLoss',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='side2_supplyLoss',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='strength9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness10',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weakness9',
            field=models.TextField(blank=True, default=''),
        ),
    ]
