# Generated by Django 6.0.5 on 2026-06-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_articles_side1_battlepressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='criticalMistakes1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='criticalMistakes2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='criticalMistakes3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='criticalMistakes4',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='criticalMistakes5',
        ),
    ]
