from django.db import models
from django.utils.text import slugify


class Articles(models.Model):

    Name = models.CharField(max_length=255, blank=True, default="")
    Year = models.CharField(max_length=30, blank=True, default="")
    Victor = models.CharField(max_length=30, blank=True, default="")
    Slug = models.SlugField(unique=True, blank=True, default="")
    Importance = models.TextField(blank=True, default="")
    Author = models.CharField(max_length=50, blank=True, default="")
    Type = models.CharField(max_length=50)
    Tag1 = models.CharField(max_length=50, blank=True, default="")
    Tag2 = models.CharField(max_length=50, blank=True, default="")
    Tag3 = models.CharField(max_length=50, blank=True, default="")
    Tag4 = models.CharField(max_length=50, blank=True, default="")
    Tag5 = models.CharField(max_length=50, blank=True, default="")

    # Before
    # Side 1
    side1_Name = models.CharField(max_length=255, blank=True, default="")
    side1_troops = models.CharField(max_length=255, blank=True, default="")
    side1_infantry = models.CharField(max_length=255, blank=True, default="")
    side1_cavalry = models.CharField(max_length=255, blank=True, default="")
    side1_veterans = models.CharField(max_length=255, blank=True, default="")
    side1_morale = models.CharField(max_length=255, blank=True, default="")
    side1_food = models.CharField(max_length=255, blank=True, default="")
    side1_supplyLoss = models.CharField(max_length=255, blank=True, default="")
    side1_armor = models.CharField(max_length=255, blank=True, default="")
    side1_mountedUnits = models.CharField(max_length=255, blank=True, default="")
    side1_mainRoute = models.CharField(max_length=255, blank=True, default="")
    side1_routeLength = models.CharField(max_length=255, blank=True, default="")
    side1_contested = models.CharField(max_length=255, blank=True, default="")
    side1_supplyDelay = models.CharField(max_length=255, blank=True, default="")
    side1_unitName1 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName2 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName3 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName4 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName5 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName6 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName7 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName8 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName9 = models.CharField(max_length=30, blank=True, default="")
    side1_unitName10 = models.CharField(max_length=30, blank=True, default="")
    side1_officer1 = models.CharField(max_length=30, blank=True, default="")
    side1_officer2 = models.CharField(max_length=30, blank=True, default="")
    side1_officer3 = models.CharField(max_length=30, blank=True, default="")
    side1_officer4 = models.CharField(max_length=30, blank=True, default="")
    side1_officer5 = models.CharField(max_length=30, blank=True, default="")
    side1_officer6 = models.CharField(max_length=30, blank=True, default="")
    side1_officer7 = models.CharField(max_length=30, blank=True, default="")
    side1_officer8 = models.CharField(max_length=30, blank=True, default="")
    side1_officer9 = models.CharField(max_length=30, blank=True, default="")
    side1_officer10 = models.CharField(max_length=30, blank=True, default="")

    # Side 2
    side2_Name = models.CharField(max_length=255, blank=True, default="")
    side2_troops = models.CharField(max_length=255, blank=True, default="")
    side2_infantry = models.CharField(max_length=255, blank=True, default="")
    side2_cavalry = models.CharField(max_length=255, blank=True, default="")
    side2_veterans = models.CharField(max_length=255, blank=True, default="")
    side2_morale = models.CharField(max_length=255, blank=True, default="")
    side2_food = models.CharField(max_length=255, blank=True, default="")
    side2_supplyLoss = models.CharField(max_length=255, blank=True, default="")
    side2_armor = models.CharField(max_length=255, blank=True, default="")
    side2_mountedUnits = models.CharField(max_length=255, blank=True, default="")
    side2_mainRoute = models.CharField(max_length=255, blank=True, default="")
    side2_routeLength = models.CharField(max_length=255, blank=True, default="")
    side2_unitName1 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName2 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName3 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName4 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName5 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName6 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName7 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName8 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName9 = models.CharField(max_length=255, blank=True, default="")
    side2_unitName10 = models.CharField(max_length=255, blank=True, default="")
    side2_officer1 = models.CharField(max_length=255, blank=True, default="")
    side2_officer2 = models.CharField(max_length=255, blank=True, default="")
    side2_officer3 = models.CharField(max_length=255, blank=True, default="")
    side2_officer4 = models.CharField(max_length=255, blank=True, default="")
    side2_officer5 = models.CharField(max_length=255, blank=True, default="")
    side2_officer6 = models.CharField(max_length=255, blank=True, default="")
    side2_officer7 = models.CharField(max_length=255, blank=True, default="")
    side2_officer8 = models.CharField(max_length=255, blank=True, default="")
    side2_officer9 = models.CharField(max_length=255, blank=True, default="")
    side2_officer10 = models.CharField(max_length=255, blank=True, default="")

    Terrain = models.CharField(max_length=255, blank=True, default="")
    Weather = models.CharField(max_length=255, blank=True, default="")
    Visibility = models.CharField(max_length=255, blank=True, default="")
    Mobility = models.CharField(max_length=255, blank=True, default="")

    # Side 1
    commander1_name = models.CharField(max_length=255, blank=True, default="")
    commander1_SuccessfulDecisions1 = models.TextField(blank=True, default="")
    commander1_SuccessfulDecisions2 = models.TextField(blank=True, default="")
    commander1_SuccessfulDecisions3 = models.TextField(blank=True, default="")
    commander1_SuccessfulDecisions4 = models.TextField(blank=True, default="")
    commander1_SuccessfulDecisions5 = models.TextField(blank=True, default="")

    commander1_FailedDecisions1 = models.TextField(blank=True, default="")
    commander1_FailedDecisions2 = models.TextField(blank=True, default="")
    commander1_FailedDecisions3 = models.TextField(blank=True, default="")
    commander1_FailedDecisions4 = models.TextField(blank=True, default="")
    commander1_FailedDecisions5 = models.TextField(blank=True, default="")

    # Side 2
    commander2_name = models.CharField(max_length=255, blank=True, default="")
    commander2_successfulDecisions1 = models.TextField(blank=True, default="")
    commander2_successfulDecisions2 = models.TextField(blank=True, default="")
    commander2_successfulDecisions3 = models.TextField(blank=True, default="")
    commander2_successfulDecisions4 = models.TextField(blank=True, default="")
    commander2_successfulDecisions5 = models.TextField(blank=True, default="")

    commander2_failedDecisions1 = models.TextField(blank=True, default="")
    commander2_failedDecisions2 = models.TextField(blank=True, default="")
    commander2_failedDecisions3 = models.TextField(blank=True, default="")
    commander2_failedDecisions4 = models.TextField(blank=True, default="")
    commander2_failedDecisions5 = models.TextField(blank=True, default="")

    # During
    TurningPoint = models.TextField()
    side1_Menance = models.TextField(blank=True, default="")
    side2_Menance = models.TextField(blank=True, default="")

    Move1 = models.TextField(blank=True, default="")
    Move2 = models.TextField(blank=True, default="")
    Move3 = models.TextField(blank=True, default="")
    Move4 = models.TextField(blank=True, default="")
    Move5 = models.TextField(blank=True, default="")
    Move6 = models.TextField(blank=True, default="")
    Move7 = models.TextField(blank=True, default="")
    Move8 = models.TextField(blank=True, default="")
    Move9 = models.TextField(blank=True, default="")
    Move10 = models.TextField(blank=True, default="")

    strength1 = models.TextField(blank=True, default="")
    strength2 = models.TextField(blank=True, default="")
    strength3 = models.TextField(blank=True, default="")
    strength4 = models.TextField(blank=True, default="")
    strength5 = models.TextField(blank=True, default="")
    strength6 = models.TextField(blank=True, default="")
    strength7 = models.TextField(blank=True, default="")
    strength8 = models.TextField(blank=True, default="")
    strength9 = models.TextField(blank=True, default="")
    strength10 = models.TextField(blank=True, default="")

    weakness1 = models.TextField(blank=True, default="")
    weakness2 = models.TextField(blank=True, default="")
    weakness3 = models.TextField(blank=True, default="")
    weakness4 = models.TextField(blank=True, default="")
    weakness5 = models.TextField(blank=True, default="")
    weakness6 = models.TextField(blank=True, default="")
    weakness7 = models.TextField(blank=True, default="")
    weakness8 = models.TextField(blank=True, default="")
    weakness9 = models.TextField(blank=True, default="")
    weakness10 = models.TextField(blank=True, default="")

    # After
    side1_casualties = models.TextField(blank=True, default="")
    side1_captured = models.TextField(blank=True, default="")
    side1_equipmentLoss = models.TextField(blank=True, default="")
    side1_supplyLoss = models.TextField(blank=True, default="")

    side2_casualties = models.TextField(blank=True, default="")
    side2_captured = models.TextField(blank=True, default="")
    side2_equipmentLoss = models.TextField(blank=True, default="")
    side2_supplyLoss = models.TextField(blank=True, default="")

    TacticalReform = models.TextField(blank=True, default="")
    DoctrineChange = models.TextField(blank=True, default="")
    MoraleEffect = models.TextField(blank=True, default="")
    HistoricalImpact = models.TextField(blank=True, default="")
    MilitaryInfluence = models.TextField(blank=True, default="")
    LongTermConsequence = models.TextField(blank=True, default="")

    def save(self, *args, **kwargs):

        if not self.Slug:
            self.Slug = slugify(self.Name)

        super().save(*args, **kwargs)

    def __str__(self):
        return self.Name
